export const SET_USERS = 'SET_USERS';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const SET_ADDRESS_EVENTS = 'SET_ADDRESS_EVENTS';
export const SELECT_ITEM = 'SELECT_ITEM';
export const COMPARE_EVENTS = 'COMPARE_EVENTS';
export const RESET_USER = 'RESET_USER';
export const CLEAR_EVENTS = 'CLEAR_EVENTS';
